FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
EXPOSE 80
WORKDIR /app
COPY ./ /app
ENTRYPOINT ["dotnet", "DM.Project.API.dll"]

ENV CORECLR_ENABLE_PROFILING=1 \
CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A} \
CORECLR_NEWRELIC_HOME=/usr/local/newrelic-netcore20-agent \
CORECLR_PROFILER_PATH=/usr/local/newrelic-netcore20-agent/libNewRelicProfiler.so \
NEW_RELIC_LICENSE_KEY=#{NewRelicKey} \
NEW_RELIC_APP_NAME=#{NewRelicAppName}

RUN apt-get update && \
    apt-get install -y gnupg && \
    echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | tee /etc/apt/sources.list.d/newrelic.list && \
    curl -L https://download.newrelic.com/548C16BF.gpg | apt-key add - && \
    apt-get update && \
    apt-get install -y newrelic-netcore20-agent && \
    rm -rf /var/lib/apt/lists/*
